"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['main-mac.py']
DATA_FILES = []
OPTIONS = {'iconfile': 'generated-2e5cecab9c32d41789f3f5fba684dc6623124f1a5129e7ef5c1671c9a6cfe173.icns'}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
