name: Build

on: [push]

jobs:

  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with: 
          python-version: '3.10.9'

      - name: Install Requirements
        run: |
          cd ${{ github.workspace }}
          pip install -r requirements.txt

      - uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: main
          script-name: main.py
          onefile: true

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: exe
          path: build/main.exe

  create-release:

    needs: build

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set
        run: |
          DATE_TIME=`date +'%Y-%m-%d-%H-%M-%S'`
          echo "DATE_TIME=${DATE_TIME}" >> $GITHUB_OUTPUT

      - uses: actions/download-artifact@v4
        with:
          name: exe
          path: artifacts

			- name: Create release
				env:
					GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

				run:
					RELEASE_NAME=Build-${{ steps.datetime.outputs.DATE_TIME }}
					TAG_NAME=build-${{ steps.datetime.outputs.DATE_TIME }}
					gh release create "$TAG_NAME" ${{ github.workspace }}/artifacts/*.exe --title "$RELEASE_NAME"
